services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssr-website
    networks:
      - masternet
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:3000/ >/dev/null 2>&1 || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  masternet:
    external: true
